/*
###############################################################
#  Generated by:      Cadence Innovus 25.10-p002_1
#  OS:                Linux x86_64(Host ID cobalt.clear8.rice.edu)
#  Generated on:      Sun Apr 12 01:38:47 2026
#  Design:            vending_top
#  Command:           saveNetlist final.v
###############################################################
*/
/////////////////////////////////////////////////////////////
// Created by: Synopsys DC Expert(TM) in wire load mode
// Version   : U-2022.12-SP7
// Date      : Sun Apr 12 01:10:45 2026
/////////////////////////////////////////////////////////////
module vending_top (
	clka, 
	clkb, 
	rst_n, 
	coin_valid, 
	coin_type, 
	sel_valid, 
	sel_id, 
	cancel, 
	dispense_valid, 
	dispense_id, 
	change_pulse, 
	change_type, 
	status_code, 
	err_code);
   input clka;
   input clkb;
   input rst_n;
   input coin_valid;
   input [1:0] coin_type;
   input sel_valid;
   input [1:0] sel_id;
   input cancel;
   output dispense_valid;
   output [1:0] dispense_id;
   output change_pulse;
   output [1:0] change_type;
   output [1:0] status_code;
   output [1:0] err_code;

   // Internal wires
   wire soldout;
   wire enough;
   wire rem_zero;
   wire bank_enough;
   wire balance_zero;
   wire can25;
   wire can10;
   wire can5;
   wire do_add_coin;
   wire do_latch_sel;
   wire do_dec_inv;
   wire do_compute_change;
   wire do_load_rem_from_bal;
   wire do_clear_balance;
   wire chg_sub_pulse;
   wire \u_fsm/n101 ;
   wire \u_fsm/n100 ;
   wire \u_fsm/n99 ;
   wire \u_fsm/n98 ;
   wire \u_fsm/n97 ;
   wire \u_fsm/n96 ;
   wire \u_fsm/n95 ;
   wire \u_fsm/n94 ;
   wire \u_fsm/n93 ;
   wire \u_fsm/n92 ;
   wire \u_fsm/n91 ;
   wire \u_fsm/n90 ;
   wire \u_fsm/n89 ;
   wire \u_fsm/n88 ;
   wire \u_fsm/n87 ;
   wire \u_fsm/n86 ;
   wire \u_fsm/n85 ;
   wire \u_fsm/n84 ;
   wire \u_fsm/n83 ;
   wire \u_fsm/n82 ;
   wire \u_fsm/n81 ;
   wire \u_fsm/n80 ;
   wire \u_fsm/n79 ;
   wire \u_fsm/n78 ;
   wire \u_fsm/n77 ;
   wire \u_fsm/n76 ;
   wire \u_fsm/n75 ;
   wire \u_fsm/n74 ;
   wire \u_fsm/n73 ;
   wire \u_fsm/n72 ;
   wire \u_fsm/n71 ;
   wire \u_fsm/n70 ;
   wire \u_fsm/n69 ;
   wire \u_fsm/n68 ;
   wire \u_fsm/n67 ;
   wire \u_fsm/n66 ;
   wire \u_fsm/n65 ;
   wire \u_fsm/n64 ;
   wire \u_fsm/n63 ;
   wire \u_fsm/n62 ;
   wire \u_fsm/n61 ;
   wire \u_fsm/n60 ;
   wire \u_fsm/n59 ;
   wire \u_fsm/n58 ;
   wire \u_fsm/n57 ;
   wire \u_fsm/n56 ;
   wire \u_fsm/n55 ;
   wire \u_fsm/n54 ;
   wire \u_fsm/n53 ;
   wire \u_fsm/n52 ;
   wire \u_fsm/n51 ;
   wire \u_fsm/n50 ;
   wire \u_fsm/n49 ;
   wire \u_fsm/n48 ;
   wire \u_fsm/n47 ;
   wire \u_fsm/n46 ;
   wire \u_fsm/n45 ;
   wire \u_fsm/n44 ;
   wire \u_fsm/n43 ;
   wire \u_fsm/n42 ;
   wire \u_fsm/n41 ;
   wire \u_fsm/n40 ;
   wire \u_fsm/n39 ;
   wire \u_fsm/n38 ;
   wire \u_fsm/n37 ;
   wire \u_fsm/n36 ;
   wire \u_fsm/n35 ;
   wire \u_fsm/n34 ;
   wire \u_fsm/N212 ;
   wire \u_fsm/N211 ;
   wire \u_fsm/N210 ;
   wire \u_fsm/N207 ;
   wire \u_fsm/N206 ;
   wire \u_fsm/N205 ;
   wire \u_fsm/N204 ;
   wire \u_fsm/N203 ;
   wire \u_fsm/N202 ;
   wire \u_fsm/N201 ;
   wire \u_fsm/N200 ;
   wire \u_fsm/N199 ;
   wire \u_fsm/N198 ;
   wire \u_fsm/chg_done_pulse ;
   wire \u_fsm/change_start_pulse ;
   wire \u_datapath/n248 ;
   wire \u_datapath/n247 ;
   wire \u_datapath/n246 ;
   wire \u_datapath/n245 ;
   wire \u_datapath/n244 ;
   wire \u_datapath/n243 ;
   wire \u_datapath/n242 ;
   wire \u_datapath/n241 ;
   wire \u_datapath/n240 ;
   wire \u_datapath/n239 ;
   wire \u_datapath/n238 ;
   wire \u_datapath/n237 ;
   wire \u_datapath/n236 ;
   wire \u_datapath/n235 ;
   wire \u_datapath/n234 ;
   wire \u_datapath/n233 ;
   wire \u_datapath/n232 ;
   wire \u_datapath/n231 ;
   wire \u_datapath/n230 ;
   wire \u_datapath/n229 ;
   wire \u_datapath/n228 ;
   wire \u_datapath/n227 ;
   wire \u_datapath/n226 ;
   wire \u_datapath/n225 ;
   wire \u_datapath/n224 ;
   wire \u_datapath/n223 ;
   wire \u_datapath/n222 ;
   wire \u_datapath/n221 ;
   wire \u_datapath/n220 ;
   wire \u_datapath/n219 ;
   wire \u_datapath/n218 ;
   wire \u_datapath/n217 ;
   wire \u_datapath/n216 ;
   wire \u_datapath/n215 ;
   wire \u_datapath/n214 ;
   wire \u_datapath/n213 ;
   wire \u_datapath/n212 ;
   wire \u_datapath/n211 ;
   wire \u_datapath/n210 ;
   wire \u_datapath/n209 ;
   wire \u_datapath/n208 ;
   wire \u_datapath/n207 ;
   wire \u_datapath/n206 ;
   wire \u_datapath/n205 ;
   wire \u_datapath/n204 ;
   wire \u_datapath/n203 ;
   wire \u_datapath/n202 ;
   wire \u_datapath/n201 ;
   wire \u_datapath/n200 ;
   wire \u_datapath/n199 ;
   wire \u_datapath/n198 ;
   wire \u_datapath/n197 ;
   wire \u_datapath/n196 ;
   wire \u_datapath/n195 ;
   wire \u_datapath/n194 ;
   wire \u_datapath/n193 ;
   wire \u_datapath/n192 ;
   wire \u_datapath/n191 ;
   wire \u_datapath/n190 ;
   wire \u_datapath/n189 ;
   wire \u_datapath/n188 ;
   wire \u_datapath/n187 ;
   wire \u_datapath/n186 ;
   wire \u_datapath/n185 ;
   wire \u_datapath/n184 ;
   wire \u_datapath/n183 ;
   wire \u_datapath/n182 ;
   wire \u_datapath/n181 ;
   wire \u_datapath/n180 ;
   wire \u_datapath/n179 ;
   wire \u_datapath/n178 ;
   wire \u_datapath/n177 ;
   wire \u_datapath/n176 ;
   wire \u_datapath/n175 ;
   wire \u_datapath/n173 ;
   wire \u_datapath/n172 ;
   wire \u_datapath/n171 ;
   wire \u_datapath/n170 ;
   wire \u_datapath/n169 ;
   wire \u_datapath/n168 ;
   wire \u_datapath/n167 ;
   wire \u_datapath/n166 ;
   wire \u_datapath/n165 ;
   wire \u_datapath/n164 ;
   wire \u_datapath/n163 ;
   wire \u_datapath/n162 ;
   wire \u_datapath/n161 ;
   wire \u_datapath/n160 ;
   wire \u_datapath/n159 ;
   wire \u_datapath/n158 ;
   wire \u_datapath/n157 ;
   wire \u_datapath/n156 ;
   wire \u_datapath/n155 ;
   wire \u_datapath/n154 ;
   wire \u_datapath/n153 ;
   wire \u_datapath/n152 ;
   wire \u_datapath/n151 ;
   wire \u_datapath/n150 ;
   wire \u_datapath/n149 ;
   wire \u_datapath/n148 ;
   wire \u_datapath/n147 ;
   wire \u_datapath/n146 ;
   wire \u_datapath/n145 ;
   wire \u_datapath/n144 ;
   wire \u_datapath/n143 ;
   wire \u_datapath/n142 ;
   wire \u_datapath/n141 ;
   wire \u_datapath/n140 ;
   wire \u_datapath/n139 ;
   wire \u_datapath/n138 ;
   wire \u_datapath/n137 ;
   wire \u_datapath/n134 ;
   wire \u_datapath/n133 ;
   wire \u_datapath/n132 ;
   wire \u_datapath/n131 ;
   wire \u_datapath/n130 ;
   wire \u_datapath/n129 ;
   wire \u_datapath/n128 ;
   wire \u_datapath/n127 ;
   wire \u_datapath/n126 ;
   wire \u_datapath/n125 ;
   wire \u_datapath/n124 ;
   wire \u_datapath/n123 ;
   wire \u_datapath/n122 ;
   wire \u_datapath/n121 ;
   wire \u_datapath/n120 ;
   wire \u_datapath/n119 ;
   wire \u_datapath/n118 ;
   wire \u_datapath/n117 ;
   wire \u_datapath/n116 ;
   wire \u_datapath/n115 ;
   wire \u_datapath/n114 ;
   wire \u_datapath/n113 ;
   wire \u_datapath/n112 ;
   wire \u_datapath/n111 ;
   wire \u_datapath/n103 ;
   wire \u_datapath/n100 ;
   wire \u_datapath/n99 ;
   wire \u_datapath/n98 ;
   wire \u_datapath/n97 ;
   wire \u_datapath/N109 ;
   wire \u_datapath/N108 ;
   wire \u_datapath/N107 ;
   wire \u_datapath/N105 ;
   wire \u_datapath/N103 ;
   wire \u_datapath/N102 ;
   wire \u_datapath/N101 ;
   wire \u_datapath/N99 ;
   wire \u_datapath/N97 ;
   wire \u_datapath/N96 ;
   wire \u_datapath/N95 ;
   wire \u_datapath/N94 ;
   wire \u_datapath/N92 ;
   wire \u_datapath/N91 ;
   wire \u_datapath/N90 ;
   wire \u_datapath/N89 ;
   wire \u_datapath/N88 ;
   wire \u_datapath/N86 ;
   wire \u_datapath/N83 ;
   wire \u_datapath/N81 ;
   wire \u_datapath/N55 ;
   wire \u_datapath/N54 ;
   wire \u_datapath/N53 ;
   wire \u_datapath/N52 ;
   wire \u_datapath/N51 ;
   wire \u_datapath/N50 ;
   wire \u_datapath/N35 ;
   wire \u_datapath/N34 ;
   wire \u_datapath/N33 ;
   wire \u_datapath/N32 ;
   wire \u_datapath/N31 ;
   wire \u_datapath/N30 ;
   wire \u_datapath/N25 ;
   wire \u_datapath/N24 ;
   wire \u_datapath/inv[0][3] ;
   wire \u_datapath/inv[0][2] ;
   wire \u_datapath/inv[0][1] ;
   wire \u_datapath/inv[0][0] ;
   wire \u_datapath/inv[1][3] ;
   wire \u_datapath/inv[1][2] ;
   wire \u_datapath/inv[1][1] ;
   wire \u_datapath/inv[1][0] ;
   wire \u_datapath/inv[2][3] ;
   wire \u_datapath/inv[2][2] ;
   wire \u_datapath/inv[2][1] ;
   wire \u_datapath/inv[2][0] ;
   wire \u_datapath/inv[3][3] ;
   wire \u_datapath/inv[3][2] ;
   wire \u_datapath/inv[3][1] ;
   wire \u_datapath/inv[3][0] ;
   wire \u_datapath/price_sel[1] ;
   wire \u_datapath/change_rem_out[1] ;
   wire \u_datapath/change_rem_out[2] ;
   wire \u_datapath/change_rem_out[3] ;
   wire \u_datapath/change_rem_out[4] ;
   wire \u_datapath/change_rem_out[5] ;
   wire \u_datapath/balance_out[1] ;
   wire \u_datapath/balance_out[2] ;
   wire \u_datapath/balance_out[3] ;
   wire \u_datapath/balance_out[4] ;
   wire \u_datapath/balance_out[5] ;
   wire \u_datapath/sub_111/carry[2] ;
   wire \u_datapath/sub_111/carry[4] ;
   wire \u_datapath/sub_111/carry[5] ;
   wire \u_datapath/sub_112/carry[2] ;
   wire \u_datapath/sub_112/carry[4] ;
   wire \u_datapath/sub_112/carry[5] ;
   wire n1;
   wire n2;
   wire n3;
   wire n4;
   wire n5;
   wire n6;
   wire n7;
   wire n8;
   wire n9;
   wire n10;
   wire n11;
   wire n12;
   wire n13;
   wire n14;
   wire n15;
   wire n16;
   wire n17;
   wire n18;
   wire n19;
   wire n20;
   wire n21;
   wire n22;
   wire n23;
   wire n24;
   wire n25;
   wire n26;
   wire n27;
   wire n28;
   wire n29;
   wire n30;
   wire n31;
   wire n32;
   wire n33;
   wire n34;
   wire n35;
   wire n36;
   wire n37;
   wire n38;
   wire n39;
   wire n40;
   wire n41;
   wire n42;
   wire n43;
   wire n44;
   wire n45;
   wire n46;
   wire n47;
   wire n48;
   wire n49;
   wire n50;
   wire n51;
   wire n52;
   wire n53;
   wire n54;
   wire n55;
   wire n56;
   wire n57;
   wire n58;
   wire n59;
   wire n60;
   wire n61;
   wire n62;
   wire n63;
   wire n64;
   wire n65;
   wire n66;
   wire n67;
   wire n68;
   wire n69;
   wire n70;
   wire n71;
   wire n72;
   wire n73;
   wire n74;
   wire n75;
   wire n76;
   wire n77;
   wire n78;
   wire n79;
   wire n80;
   wire n81;
   wire n82;
   wire n83;
   wire n84;
   wire n85;
   wire n86;
   wire n87;
   wire n88;
   wire n89;
   wire n90;
   wire n91;
   wire n92;
   wire n93;
   wire n94;
   wire n95;
   wire n96;
   wire n97;
   wire n98;
   wire n99;
   wire n100;
   wire n101;
   wire n102;
   wire n103;
   wire n104;
   wire n105;
   wire n106;
   wire n107;
   wire n108;
   wire n109;
   wire n110;
   wire n111;
   wire n112;
   wire n113;
   wire n114;
   wire n115;
   wire n116;
   wire n117;
   wire n118;
   wire n119;
   wire n120;
   wire n121;
   wire n122;
   wire n123;
   wire n124;
   wire n125;
   wire n126;
   wire n127;
   wire n128;
   wire n129;
   wire n130;
   wire n131;
   wire n132;
   wire n133;
   wire n134;
   wire n135;
   wire n136;
   wire n137;
   wire n138;
   wire n139;
   wire n140;
   wire n141;
   wire n142;
   wire n143;
   wire n144;
   wire n145;
   wire n146;
   wire n147;
   wire n148;
   wire n149;
   wire n150;
   wire n151;
   wire n152;
   wire n153;
   wire n154;
   wire n155;
   wire n156;
   wire [1:0] sel_reg_out;
   wire [1:0] chg_denom;
   wire [2:0] \u_fsm/cstate ;
   wire [2:0] \u_fsm/state ;
   wire [5:0] \u_datapath/change_bank ;
   wire [2:0] \u_datapath/coin_value ;
   wire [5:1] \u_datapath/add_94/carry ;
   wire [6:0] \u_datapath/sub_103/carry ;
   wire [6:0] \u_datapath/sub_115/carry ;
   wire [6:0] \u_datapath/sub_116/carry ;

   NOR2X1 \u_fsm/U116  (.Y(\u_fsm/n51 ),
	.B(\u_fsm/state [2]),
	.A(\u_fsm/state [1]));
   NAND2X1 \u_fsm/U115  (.Y(\u_fsm/n98 ),
	.B(n23),
	.A(\u_fsm/n51 ));
   NOR2X1 \u_fsm/U114  (.Y(\u_fsm/N198 ),
	.B(\u_fsm/n98 ),
	.A(n47));
   NOR2X1 \u_fsm/U113  (.Y(\u_fsm/N199 ),
	.B(\u_fsm/n98 ),
	.A(n50));
   NOR2X1 \u_fsm/U112  (.Y(\u_fsm/n97 ),
	.B(balance_zero),
	.A(\u_fsm/state [0]));
   NAND2X1 \u_fsm/U111  (.Y(\u_fsm/n63 ),
	.B(\u_fsm/state [2]),
	.A(\u_fsm/n41 ));
   NOR2X1 \u_fsm/U110  (.Y(\u_fsm/N200 ),
	.B(n25),
	.A(\u_fsm/n63 ));
   NAND3X1 \u_fsm/U109  (.Y(\u_fsm/n95 ),
	.C(\u_fsm/state [2]),
	.B(n63),
	.A(n65));
   OR2X1 \u_fsm/U108  (.Y(\u_fsm/n96 ),
	.B(n26),
	.A(\u_fsm/n95 ));
   NAND3X1 \u_fsm/U107  (.Y(\u_fsm/n83 ),
	.C(\u_fsm/cstate [2]),
	.B(n72),
	.A(n73));
   NOR2X1 \u_fsm/U106  (.Y(\u_fsm/N203 ),
	.B(n25),
	.A(\u_fsm/n83 ));
   OAI21X1 \u_fsm/U105  (.Y(\u_fsm/N201 ),
	.C(n32),
	.B(\u_fsm/n96 ),
	.A(n95));
   NOR2X1 \u_fsm/U104  (.Y(\u_fsm/n85 ),
	.B(rem_zero),
	.A(\u_fsm/n95 ));
   NAND2X1 \u_fsm/U103  (.Y(\u_fsm/n94 ),
	.B(n23),
	.A(\u_fsm/n85 ));
   OAI21X1 \u_fsm/U102  (.Y(\u_fsm/N202 ),
	.C(n31),
	.B(\u_fsm/n94 ),
	.A(n92));
   NOR2X1 \u_fsm/U101  (.Y(\u_fsm/n50 ),
	.B(n65),
	.A(n63));
   OR2X1 \u_fsm/U100  (.Y(\u_fsm/n93 ),
	.B(\u_fsm/state [2]),
	.A(n24));
   NOR2X1 \u_fsm/U99  (.Y(\u_fsm/N204 ),
	.B(\u_fsm/n93 ),
	.A(n61));
   NAND3X1 \u_fsm/U98  (.Y(\u_fsm/n67 ),
	.C(\u_fsm/cstate [0]),
	.B(n68),
	.A(\u_fsm/cstate [1]));
   NAND2X1 \u_fsm/U97  (.Y(\u_fsm/n71 ),
	.B(n66),
	.A(can5));
   NOR2X1 \u_fsm/U96  (.Y(\u_fsm/n80 ),
	.B(\u_fsm/cstate [2]),
	.A(\u_fsm/cstate [1]));
   NOR2X1 \u_fsm/U95  (.Y(\u_fsm/n72 ),
	.B(n70),
	.A(n73));
   NAND3X1 \u_fsm/U94  (.Y(\u_fsm/n92 ),
	.C(can25),
	.B(n23),
	.A(\u_fsm/n72 ));
   NAND3X1 \u_fsm/U93  (.Y(\u_fsm/n66 ),
	.C(\u_fsm/cstate [1]),
	.B(n68),
	.A(n73));
   NAND3X1 \u_fsm/U92  (.Y(\u_fsm/n91 ),
	.C(can10),
	.B(n23),
	.A(n67));
   NOR2X1 \u_fsm/U91  (.Y(\u_fsm/n90 ),
	.B(n41),
	.A(n40));
   OAI21X1 \u_fsm/U90  (.Y(\u_fsm/N207 ),
	.C(\u_fsm/n90 ),
	.B(\u_fsm/n71 ),
	.A(n24));
   OAI21X1 \u_fsm/U89  (.Y(\u_fsm/n89 ),
	.C(n65),
	.B(soldout),
	.A(n63));
   OAI21X1 \u_fsm/U88  (.Y(\u_fsm/n87 ),
	.C(\u_fsm/n63 ),
	.B(n62),
	.A(\u_fsm/state [2]));
   OAI22X1 \u_fsm/U87  (.Y(\u_fsm/n88 ),
	.D(n92),
	.C(n60),
	.B(n65),
	.A(\u_fsm/state [1]));
   OAI21X1 \u_fsm/U86  (.Y(\u_fsm/n86 ),
	.C(\u_fsm/n83 ),
	.B(\u_fsm/n88 ),
	.A(\u_fsm/n87 ));
   NOR2X1 \u_fsm/U85  (.Y(\u_fsm/N210 ),
	.B(\u_fsm/n86 ),
	.A(n26));
   NAND3X1 \u_fsm/U84  (.Y(\u_fsm/n84 ),
	.C(\u_fsm/n85 ),
	.B(n92),
	.A(n23));
   OR2X1 \u_fsm/U83  (.Y(\u_fsm/n38 ),
	.B(\u_fsm/state [2]),
	.A(\u_fsm/state [0]));
   NAND2X1 \u_fsm/U82  (.Y(\u_fsm/n48 ),
	.B(\u_fsm/state [1]),
	.A(soldout));
   NOR3X1 \u_fsm/U81  (.Y(\u_fsm/N212 ),
	.C(\u_fsm/n48 ),
	.B(\u_fsm/n38 ),
	.A(n24));
   NOR2X1 \u_fsm/U80  (.Y(\u_fsm/n81 ),
	.B(\u_fsm/N212 ),
	.A(n42));
   NAND3X1 \u_fsm/U79  (.Y(\u_fsm/n82 ),
	.C(\u_fsm/state [2]),
	.B(n23),
	.A(\u_fsm/n50 ));
   AOI21X1 \u_fsm/U78  (.Y(\u_fsm/N211 ),
	.C(n71),
	.B(\u_fsm/n82 ),
	.A(\u_fsm/n81 ));
   OR2X1 \u_fsm/U77  (.Y(\u_fsm/n74 ),
	.B(\u_fsm/change_start_pulse ),
	.A(\u_fsm/cstate [0]));
   NAND2X1 \u_fsm/U76  (.Y(\u_fsm/n79 ),
	.B(n68),
	.A(n73));
   OAI21X1 \u_fsm/U75  (.Y(\u_fsm/n78 ),
	.C(\u_fsm/n71 ),
	.B(\u_fsm/n79 ),
	.A(can10));
   OAI21X1 \u_fsm/U74  (.Y(\u_fsm/n76 ),
	.C(n95),
	.B(\u_fsm/n78 ),
	.A(\u_fsm/n77 ));
   OAI21X1 \u_fsm/U73  (.Y(\u_fsm/n75 ),
	.C(\u_fsm/n76 ),
	.B(n70),
	.A(\u_fsm/cstate [0]));
   OAI21X1 \u_fsm/U72  (.Y(\u_fsm/n73 ),
	.C(\u_fsm/n75 ),
	.B(\u_fsm/n74 ),
	.A(n70));
   NOR2X1 \u_fsm/U71  (.Y(\u_fsm/n101 ),
	.B(\u_fsm/n73 ),
	.A(n26));
   NOR2X1 \u_fsm/U70  (.Y(\u_fsm/n69 ),
	.B(n69),
	.A(can25));
   NAND2X1 \u_fsm/U69  (.Y(\u_fsm/n70 ),
	.B(\u_fsm/n66 ),
	.A(\u_fsm/n71 ));
   OAI21X1 \u_fsm/U68  (.Y(\u_fsm/n68 ),
	.C(n95),
	.B(\u_fsm/n70 ),
	.A(\u_fsm/n69 ));
   NOR2X1 \u_fsm/U67  (.Y(\u_fsm/n100 ),
	.B(\u_fsm/n68 ),
	.A(n26));
   NAND3X1 \u_fsm/U66  (.Y(\u_fsm/n65 ),
	.C(\u_fsm/n67 ),
	.B(\u_fsm/n66 ),
	.A(n69));
   AOI22X1 \u_fsm/U65  (.Y(\u_fsm/n64 ),
	.D(n96),
	.C(n66),
	.B(\u_fsm/n65 ),
	.A(rem_zero));
   NOR2X1 \u_fsm/U64  (.Y(\u_fsm/n99 ),
	.B(n25),
	.A(\u_fsm/n64 ));
   OAI21X1 \u_fsm/U63  (.Y(\u_fsm/n53 ),
	.C(\u_fsm/n63 ),
	.B(n61),
	.A(cancel));
   NOR2X1 \u_fsm/U62  (.Y(\u_fsm/n37 ),
	.B(coin_valid),
	.A(\u_fsm/state [1]));
   OAI22X1 \u_fsm/U61  (.Y(\u_fsm/n61 ),
	.D(n48),
	.C(\u_fsm/state [0]),
	.B(n52),
	.A(n65));
   NAND2X1 \u_fsm/U60  (.Y(\u_fsm/n62 ),
	.B(n61),
	.A(\u_fsm/n48 ));
   AOI21X1 \u_fsm/U59  (.Y(\u_fsm/n57 ),
	.C(\u_fsm/n62 ),
	.B(n50),
	.A(\u_fsm/n61 ));
   OR2X1 \u_fsm/U58  (.Y(\u_fsm/n59 ),
	.B(\u_fsm/chg_done_pulse ),
	.A(\u_fsm/state [1]));
   NAND2X1 \u_fsm/U57  (.Y(\u_fsm/n60 ),
	.B(\u_fsm/state [0]),
	.A(\u_fsm/state [2]));
   OAI21X1 \u_fsm/U56  (.Y(\u_fsm/n58 ),
	.C(n60),
	.B(\u_fsm/n60 ),
	.A(\u_fsm/n59 ));
   OAI21X1 \u_fsm/U55  (.Y(\u_fsm/n54 ),
	.C(n59),
	.B(\u_fsm/n57 ),
	.A(\u_fsm/state [2]));
   NAND2X1 \u_fsm/U54  (.Y(\u_fsm/n39 ),
	.B(n52),
	.A(n50));
   OR2X1 \u_fsm/U53  (.Y(\u_fsm/n56 ),
	.B(n48),
	.A(\u_fsm/n39 ));
   OAI21X1 \u_fsm/U52  (.Y(\u_fsm/n55 ),
	.C(n23),
	.B(\u_fsm/n56 ),
	.A(\u_fsm/n38 ));
   OAI21X1 \u_fsm/U51  (.Y(\u_fsm/n52 ),
	.C(n46),
	.B(\u_fsm/n54 ),
	.A(\u_fsm/n53 ));
   NAND2X1 \u_fsm/U50  (.Y(\u_fsm/n49 ),
	.B(\u_fsm/n39 ),
	.A(\u_fsm/state [0]));
   NAND3X1 \u_fsm/U49  (.Y(\u_fsm/n42 ),
	.C(\u_fsm/state [2]),
	.B(n52),
	.A(\u_fsm/n50 ));
   OAI21X1 \u_fsm/U48  (.Y(\u_fsm/n44 ),
	.C(\u_fsm/n42 ),
	.B(\u_fsm/n49 ),
	.A(n64));
   NAND2X1 \u_fsm/U47  (.Y(\u_fsm/n47 ),
	.B(\u_fsm/n48 ),
	.A(n48));
   AOI21X1 \u_fsm/U46  (.Y(\u_fsm/n46 ),
	.C(\u_fsm/n47 ),
	.B(\u_fsm/state [1]),
	.A(enough));
   OAI22X1 \u_fsm/U45  (.Y(\u_fsm/n45 ),
	.D(\u_fsm/n38 ),
	.C(\u_fsm/n46 ),
	.B(n60),
	.A(bank_enough));
   OAI21X1 \u_fsm/U44  (.Y(\u_fsm/n43 ),
	.C(n46),
	.B(\u_fsm/n45 ),
	.A(\u_fsm/n44 ));
   NOR2X1 \u_fsm/U43  (.Y(\u_fsm/n40 ),
	.B(\u_fsm/n41 ),
	.A(n51));
   OAI21X1 \u_fsm/U42  (.Y(\u_fsm/n35 ),
	.C(\u_fsm/n40 ),
	.B(n64),
	.A(\u_fsm/n39 ));
   OAI21X1 \u_fsm/U41  (.Y(\u_fsm/n36 ),
	.C(n59),
	.B(\u_fsm/n38 ),
	.A(\u_fsm/n37 ));
   OAI21X1 \u_fsm/U40  (.Y(\u_fsm/n34 ),
	.C(n46),
	.B(\u_fsm/n36 ),
	.A(\u_fsm/n35 ));
   AND2X2 \u_fsm/U6  (.Y(\u_fsm/n41 ),
	.B(\u_fsm/state [1]),
	.A(\u_fsm/n97 ));
   AND2X2 \u_fsm/U5  (.Y(\u_fsm/N205 ),
	.B(n23),
	.A(sel_reg_out[0]));
   AND2X2 \u_fsm/U4  (.Y(\u_fsm/N206 ),
	.B(n23),
	.A(sel_reg_out[1]));
   AND2X2 \u_fsm/U3  (.Y(\u_fsm/n77 ),
	.B(can25),
	.A(\u_fsm/n80 ));
   DFFNEGX1 \u_fsm/do_compute_change_reg  (.Q(do_compute_change),
	.D(\u_fsm/N204 ),
	.CLK(clka));
   DFFNEGX1 \u_fsm/do_dec_inv_reg  (.Q(do_dec_inv),
	.D(\u_fsm/N204 ),
	.CLK(clka));
   DFFNEGX1 \u_fsm/do_latch_sel_reg  (.Q(do_latch_sel),
	.D(\u_fsm/N199 ),
	.CLK(clka));
   DFFNEGX1 \u_fsm/do_add_coin_reg  (.Q(do_add_coin),
	.D(\u_fsm/N198 ),
	.CLK(clka));
   DFFNEGX1 \u_fsm/err_code_reg[0]  (.Q(err_code[0]),
	.D(\u_fsm/N212 ),
	.CLK(clka));
   DFFNEGX1 \u_fsm/err_code_reg[1]  (.Q(err_code[1]),
	.D(n42),
	.CLK(clka));
   DFFNEGX1 \u_fsm/chg_sub_pulse_reg  (.Q(chg_sub_pulse),
	.D(\u_fsm/N207 ),
	.CLK(clka));
   DFFNEGX1 \u_fsm/chg_denom_reg[0]  (.Q(chg_denom[0]),
	.D(n41),
	.CLK(clka));
   DFFNEGX1 \u_fsm/chg_denom_reg[1]  (.Q(chg_denom[1]),
	.D(n40),
	.CLK(clka));
   DFFNEGX1 \u_fsm/do_clear_balance_reg  (.Q(do_clear_balance),
	.D(\u_fsm/N201 ),
	.CLK(clka));
   DFFNEGX1 \u_fsm/change_type_reg[0]  (.Q(change_type[0]),
	.D(n41),
	.CLK(clka));
   DFFNEGX1 \u_fsm/change_pulse_reg  (.Q(change_pulse),
	.D(\u_fsm/N207 ),
	.CLK(clka));
   DFFNEGX1 \u_fsm/status_code_reg[1]  (.Q(status_code[1]),
	.D(\u_fsm/N211 ),
	.CLK(clka));
   DFFNEGX1 \u_fsm/do_load_rem_from_bal_reg  (.Q(do_load_rem_from_bal),
	.D(\u_fsm/N200 ),
	.CLK(clka));
   DFFNEGX1 \u_fsm/status_code_reg[0]  (.Q(status_code[0]),
	.D(\u_fsm/N210 ),
	.CLK(clka));
   DFFNEGX1 \u_fsm/dispense_valid_reg  (.Q(dispense_valid),
	.D(\u_fsm/N204 ),
	.CLK(clka));
   DFFNEGX1 \u_fsm/state_reg[1]  (.Q(\u_fsm/state [1]),
	.D(n44),
	.CLK(clka));
   DFFNEGX1 \u_fsm/state_reg[2]  (.Q(\u_fsm/state [2]),
	.D(n43),
	.CLK(clka));
   DFFNEGX1 \u_fsm/state_reg[0]  (.Q(\u_fsm/state [0]),
	.D(n45),
	.CLK(clka));
   DFFNEGX1 \u_fsm/chg_done_pulse_reg  (.Q(\u_fsm/chg_done_pulse ),
	.D(\u_fsm/N203 ),
	.CLK(clka));
   DFFNEGX1 \u_fsm/cstate_reg[2]  (.Q(\u_fsm/cstate [2]),
	.D(\u_fsm/n99 ),
	.CLK(clka));
   DFFNEGX1 \u_fsm/change_type_reg[1]  (.Q(change_type[1]),
	.D(n40),
	.CLK(clka));
   DFFNEGX1 \u_fsm/cstate_reg[1]  (.Q(\u_fsm/cstate [1]),
	.D(\u_fsm/n100 ),
	.CLK(clka));
   DFFNEGX1 \u_fsm/cstate_reg[0]  (.Q(\u_fsm/cstate [0]),
	.D(\u_fsm/n101 ),
	.CLK(clka));
   DFFNEGX1 \u_fsm/change_start_pulse_reg  (.Q(\u_fsm/change_start_pulse ),
	.D(\u_fsm/N202 ),
	.CLK(clka));
   DFFNEGX1 \u_fsm/dispense_id_reg[0]  (.Q(dispense_id[0]),
	.D(\u_fsm/N205 ),
	.CLK(clka));
   DFFNEGX1 \u_fsm/dispense_id_reg[1]  (.Q(dispense_id[1]),
	.D(\u_fsm/N206 ),
	.CLK(clka));
   NOR2X1 \u_datapath/U274  (.Y(\u_datapath/n211 ),
	.B(\u_datapath/change_rem_out[4] ),
	.A(\u_datapath/change_rem_out[5] ));
   NOR2X1 \u_datapath/U273  (.Y(\u_datapath/n212 ),
	.B(\u_datapath/change_rem_out[1] ),
	.A(\u_datapath/change_rem_out[2] ));
   NAND3X1 \u_datapath/U272  (.Y(\u_datapath/n207 ),
	.C(\u_datapath/n212 ),
	.B(n101),
	.A(\u_datapath/n211 ));
   NOR2X1 \u_datapath/U271  (.Y(\u_datapath/n209 ),
	.B(\u_datapath/change_bank [4]),
	.A(\u_datapath/change_bank [5]));
   NOR2X1 \u_datapath/U270  (.Y(\u_datapath/n210 ),
	.B(\u_datapath/change_bank [1]),
	.A(\u_datapath/change_bank [2]));
   NAND3X1 \u_datapath/U269  (.Y(\u_datapath/n208 ),
	.C(\u_datapath/n210 ),
	.B(n121),
	.A(\u_datapath/n209 ));
   NOR2X1 \u_datapath/U268  (.Y(rem_zero),
	.B(\u_datapath/N86 ),
	.A(\u_datapath/n207 ));
   AOI21X1 \u_datapath/U267  (.Y(can5),
	.C(rem_zero),
	.B(n126),
	.A(n120));
   NOR2X1 \u_datapath/U266  (.Y(\u_datapath/coin_value [1]),
	.B(n49),
	.A(coin_type[1]));
   NAND3X1 \u_datapath/U265  (.Y(\u_datapath/n205 ),
	.C(n115),
	.B(n113),
	.A(n114));
   NAND3X1 \u_datapath/U264  (.Y(\u_datapath/n206 ),
	.C(n118),
	.B(n116),
	.A(n117));
   NOR2X1 \u_datapath/U263  (.Y(balance_zero),
	.B(\u_datapath/n206 ),
	.A(\u_datapath/n205 ));
   NOR2X1 \u_datapath/U262  (.Y(\u_datapath/n99 ),
	.B(sel_reg_out[0]),
	.A(n112));
   NOR2X1 \u_datapath/U261  (.Y(\u_datapath/n100 ),
	.B(n108),
	.A(n112));
   AOI22X1 \u_datapath/U260  (.Y(\u_datapath/n203 ),
	.D(\u_datapath/n100 ),
	.C(\u_datapath/inv[3][3] ),
	.B(\u_datapath/n99 ),
	.A(\u_datapath/inv[2][3] ));
   NOR2X1 \u_datapath/U259  (.Y(\u_datapath/n97 ),
	.B(sel_reg_out[1]),
	.A(sel_reg_out[0]));
   NOR2X1 \u_datapath/U258  (.Y(\u_datapath/n98 ),
	.B(sel_reg_out[1]),
	.A(n108));
   AOI22X1 \u_datapath/U257  (.Y(\u_datapath/n204 ),
	.D(\u_datapath/n98 ),
	.C(\u_datapath/inv[1][3] ),
	.B(\u_datapath/n97 ),
	.A(\u_datapath/inv[0][3] ));
   NAND2X1 \u_datapath/U256  (.Y(\u_datapath/n127 ),
	.B(\u_datapath/n204 ),
	.A(\u_datapath/n203 ));
   AOI22X1 \u_datapath/U255  (.Y(\u_datapath/n201 ),
	.D(\u_datapath/n100 ),
	.C(\u_datapath/inv[3][0] ),
	.B(\u_datapath/n99 ),
	.A(\u_datapath/inv[2][0] ));
   AOI22X1 \u_datapath/U254  (.Y(\u_datapath/n202 ),
	.D(\u_datapath/n98 ),
	.C(\u_datapath/inv[1][0] ),
	.B(\u_datapath/n97 ),
	.A(\u_datapath/inv[0][0] ));
   AOI22X1 \u_datapath/U253  (.Y(\u_datapath/n199 ),
	.D(\u_datapath/n100 ),
	.C(\u_datapath/inv[3][1] ),
	.B(\u_datapath/n99 ),
	.A(\u_datapath/inv[2][1] ));
   AOI22X1 \u_datapath/U252  (.Y(\u_datapath/n200 ),
	.D(\u_datapath/n98 ),
	.C(\u_datapath/inv[1][1] ),
	.B(\u_datapath/n97 ),
	.A(\u_datapath/inv[0][1] ));
   NAND2X1 \u_datapath/U251  (.Y(\u_datapath/n118 ),
	.B(\u_datapath/n123 ),
	.A(\u_datapath/n122 ));
   AOI22X1 \u_datapath/U250  (.Y(\u_datapath/n197 ),
	.D(\u_datapath/n100 ),
	.C(\u_datapath/inv[3][2] ),
	.B(\u_datapath/n99 ),
	.A(\u_datapath/inv[2][2] ));
   AOI22X1 \u_datapath/U249  (.Y(\u_datapath/n198 ),
	.D(\u_datapath/n98 ),
	.C(\u_datapath/inv[1][2] ),
	.B(\u_datapath/n97 ),
	.A(\u_datapath/inv[0][2] ));
   NAND2X1 \u_datapath/U248  (.Y(\u_datapath/n119 ),
	.B(\u_datapath/n198 ),
	.A(\u_datapath/n197 ));
   NOR3X1 \u_datapath/U247  (.Y(soldout),
	.C(\u_datapath/n119 ),
	.B(\u_datapath/n118 ),
	.A(\u_datapath/n127 ));
   NOR2X1 \u_datapath/U246  (.Y(\u_datapath/n185 ),
	.B(chg_denom[0]),
	.A(n57));
   NAND2X1 \u_datapath/U244  (.Y(\u_datapath/n196 ),
	.B(n3),
	.A(n54));
   OAI21X1 \u_datapath/U243  (.Y(\u_datapath/n195 ),
	.C(chg_sub_pulse),
	.B(\u_datapath/n196 ),
	.A(n1));
   NOR2X1 \u_datapath/U241  (.Y(\u_datapath/n176 ),
	.B(n25),
	.A(n4));
   AOI22X1 \u_datapath/U240  (.Y(\u_datapath/n194 ),
	.D(n1),
	.C(\u_datapath/N92 ),
	.B(n22),
	.A(n126));
   OAI21X1 \u_datapath/U239  (.Y(\u_datapath/n193 ),
	.C(\u_datapath/n194 ),
	.B(\u_datapath/N92 ),
	.A(n54));
   NAND2X1 \u_datapath/U238  (.Y(\u_datapath/n192 ),
	.B(\u_datapath/n193 ),
	.A(\u_datapath/n176 ));
   OAI21X1 \u_datapath/U237  (.Y(\u_datapath/n248 ),
	.C(\u_datapath/n192 ),
	.B(n126),
	.A(n21));
   OAI21X1 \u_datapath/U236  (.Y(\u_datapath/n190 ),
	.C(n23),
	.B(n123),
	.A(n3));
   AOI22X1 \u_datapath/U235  (.Y(\u_datapath/n191 ),
	.D(\u_datapath/n185 ),
	.C(\u_datapath/N81 ),
	.B(n1),
	.A(n124));
   OAI21X1 \u_datapath/U234  (.Y(\u_datapath/n189 ),
	.C(n21),
	.B(n55),
	.A(\u_datapath/n190 ));
   OAI21X1 \u_datapath/U233  (.Y(\u_datapath/n247 ),
	.C(\u_datapath/n189 ),
	.B(n124),
	.A(n21));
   AOI22X1 \u_datapath/U232  (.Y(\u_datapath/n188 ),
	.D(n1),
	.C(\u_datapath/N94 ),
	.B(n22),
	.A(n122));
   OAI21X1 \u_datapath/U231  (.Y(\u_datapath/n187 ),
	.C(\u_datapath/n188 ),
	.B(n18),
	.A(n54));
   NAND2X1 \u_datapath/U230  (.Y(\u_datapath/n186 ),
	.B(\u_datapath/n187 ),
	.A(\u_datapath/n176 ));
   OAI21X1 \u_datapath/U229  (.Y(\u_datapath/n246 ),
	.C(\u_datapath/n186 ),
	.B(n20),
	.A(n21));
   OAI21X1 \u_datapath/U228  (.Y(\u_datapath/n183 ),
	.C(n23),
	.B(n119),
	.A(n3));
   AOI22X1 \u_datapath/U227  (.Y(\u_datapath/n184 ),
	.D(\u_datapath/n185 ),
	.C(\u_datapath/N83 ),
	.B(n1),
	.A(\u_datapath/N95 ));
   OAI21X1 \u_datapath/U226  (.Y(\u_datapath/n182 ),
	.C(n21),
	.B(n56),
	.A(\u_datapath/n183 ));
   OAI21X1 \u_datapath/U225  (.Y(\u_datapath/n245 ),
	.C(\u_datapath/n182 ),
	.B(n121),
	.A(n21));
   AOI22X1 \u_datapath/U224  (.Y(\u_datapath/n181 ),
	.D(n1),
	.C(\u_datapath/N96 ),
	.B(n22),
	.A(\u_datapath/N108 ));
   OAI21X1 \u_datapath/U223  (.Y(\u_datapath/n180 ),
	.C(\u_datapath/n181 ),
	.B(n15),
	.A(n54));
   NAND2X1 \u_datapath/U222  (.Y(\u_datapath/n179 ),
	.B(\u_datapath/n180 ),
	.A(\u_datapath/n176 ));
   OAI21X1 \u_datapath/U221  (.Y(\u_datapath/n244 ),
	.C(\u_datapath/n179 ),
	.B(n19),
	.A(n21));
   AOI22X1 \u_datapath/U220  (.Y(\u_datapath/n178 ),
	.D(n1),
	.C(\u_datapath/N97 ),
	.B(n22),
	.A(\u_datapath/N109 ));
   OAI21X1 \u_datapath/U219  (.Y(\u_datapath/n177 ),
	.C(\u_datapath/n178 ),
	.B(n17),
	.A(n54));
   NAND2X1 \u_datapath/U218  (.Y(\u_datapath/n175 ),
	.B(\u_datapath/n177 ),
	.A(\u_datapath/n176 ));
   OAI21X1 \u_datapath/U217  (.Y(\u_datapath/n243 ),
	.C(\u_datapath/n175 ),
	.B(n125),
	.A(n21));
   NAND2X1 \u_datapath/U216  (.Y(\u_datapath/n173 ),
	.B(coin_valid),
	.A(do_add_coin));
   NAND3X1 \u_datapath/U215  (.Y(\u_datapath/n165 ),
	.C(\u_datapath/n173 ),
	.B(n58),
	.A(rst_n));
   NAND3X1 \u_datapath/U214  (.Y(\u_datapath/n172 ),
	.C(\u_datapath/n165 ),
	.B(n58),
	.A(rst_n));
   NAND2X1 \u_datapath/U213  (.Y(\u_datapath/n171 ),
	.B(n35),
	.A(\u_datapath/N30 ));
   OAI21X1 \u_datapath/U212  (.Y(\u_datapath/n242 ),
	.C(\u_datapath/n171 ),
	.B(\u_datapath/n165 ),
	.A(n118));
   NAND2X1 \u_datapath/U211  (.Y(\u_datapath/n170 ),
	.B(n35),
	.A(\u_datapath/N31 ));
   OAI21X1 \u_datapath/U210  (.Y(\u_datapath/n241 ),
	.C(\u_datapath/n170 ),
	.B(\u_datapath/n165 ),
	.A(n117));
   NAND2X1 \u_datapath/U209  (.Y(\u_datapath/n169 ),
	.B(n35),
	.A(\u_datapath/N32 ));
   OAI21X1 \u_datapath/U208  (.Y(\u_datapath/n240 ),
	.C(\u_datapath/n169 ),
	.B(\u_datapath/n165 ),
	.A(n116));
   NAND2X1 \u_datapath/U207  (.Y(\u_datapath/n168 ),
	.B(n35),
	.A(\u_datapath/N33 ));
   OAI21X1 \u_datapath/U206  (.Y(\u_datapath/n239 ),
	.C(\u_datapath/n168 ),
	.B(\u_datapath/n165 ),
	.A(n115));
   NAND2X1 \u_datapath/U205  (.Y(\u_datapath/n167 ),
	.B(n35),
	.A(\u_datapath/N34 ));
   OAI21X1 \u_datapath/U204  (.Y(\u_datapath/n238 ),
	.C(\u_datapath/n167 ),
	.B(\u_datapath/n165 ),
	.A(n114));
   NAND2X1 \u_datapath/U203  (.Y(\u_datapath/n166 ),
	.B(n35),
	.A(\u_datapath/N35 ));
   OAI21X1 \u_datapath/U202  (.Y(\u_datapath/n237 ),
	.C(\u_datapath/n166 ),
	.B(\u_datapath/n165 ),
	.A(n113));
   OR2X1 \u_datapath/U201  (.Y(\u_datapath/n162 ),
	.B(n26),
	.A(do_latch_sel));
   NAND3X1 \u_datapath/U200  (.Y(\u_datapath/n164 ),
	.C(sel_id[1]),
	.B(rst_n),
	.A(\u_datapath/n162 ));
   OAI21X1 \u_datapath/U199  (.Y(\u_datapath/n236 ),
	.C(\u_datapath/n164 ),
	.B(\u_datapath/n162 ),
	.A(n112));
   NAND3X1 \u_datapath/U198  (.Y(\u_datapath/n163 ),
	.C(sel_id[0]),
	.B(rst_n),
	.A(\u_datapath/n162 ));
   OAI21X1 \u_datapath/U197  (.Y(\u_datapath/n235 ),
	.C(\u_datapath/n163 ),
	.B(\u_datapath/n162 ),
	.A(n108));
   NOR2X1 \u_datapath/U196  (.Y(\u_datapath/n161 ),
	.B(do_compute_change),
	.A(do_load_rem_from_bal));
   NAND3X1 \u_datapath/U195  (.Y(\u_datapath/n159 ),
	.C(\u_datapath/n161 ),
	.B(n58),
	.A(n4));
   NAND3X1 \u_datapath/U194  (.Y(\u_datapath/n157 ),
	.C(\u_datapath/n159 ),
	.B(n58),
	.A(rst_n));
   NOR2X1 \u_datapath/U193  (.Y(\u_datapath/n132 ),
	.B(n53),
	.A(\u_datapath/n157 ));
   AOI22X1 \u_datapath/U192  (.Y(\u_datapath/n160 ),
	.D(n1),
	.C(\u_datapath/N86 ),
	.B(n22),
	.A(n99));
   OAI21X1 \u_datapath/U191  (.Y(\u_datapath/n158 ),
	.C(\u_datapath/n160 ),
	.B(\u_datapath/N86 ),
	.A(n54));
   AOI22X1 \u_datapath/U190  (.Y(\u_datapath/n153 ),
	.D(n33),
	.C(\u_datapath/N86 ),
	.B(\u_datapath/n158 ),
	.A(\u_datapath/n132 ));
   NAND2X1 \u_datapath/U189  (.Y(\u_datapath/n156 ),
	.B(chg_denom[0]),
	.A(chg_denom[1]));
   AOI21X1 \u_datapath/U188  (.Y(\u_datapath/n155 ),
	.C(\u_datapath/n157 ),
	.B(chg_sub_pulse),
	.A(\u_datapath/n156 ));
   NOR2X1 \u_datapath/U187  (.Y(\u_datapath/n130 ),
	.B(do_load_rem_from_bal),
	.A(n34));
   AOI22X1 \u_datapath/U186  (.Y(\u_datapath/n154 ),
	.D(\u_datapath/n131 ),
	.C(\u_datapath/N50 ),
	.B(\u_datapath/n130 ),
	.A(\u_datapath/N50 ));
   NAND2X1 \u_datapath/U185  (.Y(\u_datapath/n234 ),
	.B(\u_datapath/n154 ),
	.A(\u_datapath/n153 ));
   AOI22X1 \u_datapath/U184  (.Y(\u_datapath/n152 ),
	.D(n1),
	.C(n97),
	.B(n22),
	.A(\u_datapath/N99 ));
   OAI21X1 \u_datapath/U183  (.Y(\u_datapath/n151 ),
	.C(\u_datapath/n152 ),
	.B(n12),
	.A(n54));
   AOI22X1 \u_datapath/U182  (.Y(\u_datapath/n149 ),
	.D(n33),
	.C(\u_datapath/change_rem_out[1] ),
	.B(\u_datapath/n151 ),
	.A(\u_datapath/n132 ));
   AOI22X1 \u_datapath/U181  (.Y(\u_datapath/n150 ),
	.D(\u_datapath/n131 ),
	.C(\u_datapath/balance_out[1] ),
	.B(\u_datapath/n130 ),
	.A(\u_datapath/N51 ));
   NAND2X1 \u_datapath/U180  (.Y(\u_datapath/n233 ),
	.B(\u_datapath/n150 ),
	.A(\u_datapath/n149 ));
   AOI22X1 \u_datapath/U179  (.Y(\u_datapath/n148 ),
	.D(n1),
	.C(\u_datapath/N88 ),
	.B(n22),
	.A(n91));
   OAI21X1 \u_datapath/U178  (.Y(\u_datapath/n147 ),
	.C(\u_datapath/n148 ),
	.B(n13),
	.A(n54));
   AOI22X1 \u_datapath/U177  (.Y(\u_datapath/n145 ),
	.D(n33),
	.C(\u_datapath/change_rem_out[2] ),
	.B(\u_datapath/n147 ),
	.A(\u_datapath/n132 ));
   AOI22X1 \u_datapath/U176  (.Y(\u_datapath/n146 ),
	.D(\u_datapath/n131 ),
	.C(\u_datapath/balance_out[2] ),
	.B(\u_datapath/n130 ),
	.A(\u_datapath/N52 ));
   NAND2X1 \u_datapath/U175  (.Y(\u_datapath/n232 ),
	.B(\u_datapath/n146 ),
	.A(\u_datapath/n145 ));
   AOI22X1 \u_datapath/U174  (.Y(\u_datapath/n144 ),
	.D(n1),
	.C(\u_datapath/N89 ),
	.B(n22),
	.A(\u_datapath/N101 ));
   OAI21X1 \u_datapath/U173  (.Y(\u_datapath/n143 ),
	.C(\u_datapath/n144 ),
	.B(n14),
	.A(n54));
   AOI22X1 \u_datapath/U172  (.Y(\u_datapath/n141 ),
	.D(n33),
	.C(\u_datapath/change_rem_out[3] ),
	.B(\u_datapath/n143 ),
	.A(\u_datapath/n132 ));
   AOI22X1 \u_datapath/U171  (.Y(\u_datapath/n142 ),
	.D(\u_datapath/n131 ),
	.C(\u_datapath/balance_out[3] ),
	.B(\u_datapath/n130 ),
	.A(\u_datapath/N53 ));
   NAND2X1 \u_datapath/U170  (.Y(\u_datapath/n231 ),
	.B(\u_datapath/n142 ),
	.A(\u_datapath/n141 ));
   AOI22X1 \u_datapath/U169  (.Y(\u_datapath/n140 ),
	.D(n1),
	.C(\u_datapath/N90 ),
	.B(n22),
	.A(\u_datapath/N102 ));
   OAI21X1 \u_datapath/U168  (.Y(\u_datapath/n139 ),
	.C(\u_datapath/n140 ),
	.B(n11),
	.A(n54));
   AOI22X1 \u_datapath/U167  (.Y(\u_datapath/n137 ),
	.D(n33),
	.C(\u_datapath/change_rem_out[4] ),
	.B(\u_datapath/n139 ),
	.A(\u_datapath/n132 ));
   AOI22X1 \u_datapath/U166  (.Y(\u_datapath/n138 ),
	.D(\u_datapath/n131 ),
	.C(\u_datapath/balance_out[4] ),
	.B(\u_datapath/n130 ),
	.A(\u_datapath/N54 ));
   NAND2X1 \u_datapath/U165  (.Y(\u_datapath/n230 ),
	.B(\u_datapath/n138 ),
	.A(\u_datapath/n137 ));
   AOI22X1 \u_datapath/U164  (.Y(\u_datapath/n134 ),
	.D(n1),
	.C(\u_datapath/N91 ),
	.B(n22),
	.A(\u_datapath/N103 ));
   OAI21X1 \u_datapath/U163  (.Y(\u_datapath/n133 ),
	.C(\u_datapath/n134 ),
	.B(n16),
	.A(n54));
   AOI22X1 \u_datapath/U162  (.Y(\u_datapath/n128 ),
	.D(n33),
	.C(\u_datapath/change_rem_out[5] ),
	.B(\u_datapath/n133 ),
	.A(\u_datapath/n132 ));
   AOI22X1 \u_datapath/U161  (.Y(\u_datapath/n129 ),
	.D(\u_datapath/n131 ),
	.C(\u_datapath/balance_out[5] ),
	.B(\u_datapath/n130 ),
	.A(\u_datapath/N55 ));
   NAND2X1 \u_datapath/U160  (.Y(\u_datapath/n229 ),
	.B(\u_datapath/n129 ),
	.A(\u_datapath/n128 ));
   OAI21X1 \u_datapath/U159  (.Y(\u_datapath/n126 ),
	.C(\u_datapath/n127 ),
	.B(\u_datapath/n119 ),
	.A(\u_datapath/n118 ));
   NAND2X1 \u_datapath/U158  (.Y(\u_datapath/n125 ),
	.B(n75),
	.A(do_dec_inv));
   OAI21X1 \u_datapath/U157  (.Y(\u_datapath/n116 ),
	.C(n23),
	.B(\u_datapath/n125 ),
	.A(n111));
   OAI22X1 \u_datapath/U156  (.Y(\u_datapath/n228 ),
	.D(\u_datapath/n116 ),
	.C(n74),
	.B(n36),
	.A(\u_datapath/n111 ));
   OAI21X1 \u_datapath/U155  (.Y(\u_datapath/n114 ),
	.C(n23),
	.B(\u_datapath/n125 ),
	.A(n106));
   NAND2X1 \u_datapath/U154  (.Y(\u_datapath/n124 ),
	.B(rst_n),
	.A(\u_datapath/n122 ));
   OAI22X1 \u_datapath/U153  (.Y(\u_datapath/n227 ),
	.D(\u_datapath/n124 ),
	.C(n37),
	.B(\u_datapath/n114 ),
	.A(n86));
   OAI22X1 \u_datapath/U152  (.Y(\u_datapath/n226 ),
	.D(\u_datapath/n124 ),
	.C(n36),
	.B(\u_datapath/n116 ),
	.A(n89));
   OAI21X1 \u_datapath/U151  (.Y(\u_datapath/n113 ),
	.C(n23),
	.B(\u_datapath/n125 ),
	.A(n107));
   OAI22X1 \u_datapath/U150  (.Y(\u_datapath/n225 ),
	.D(\u_datapath/n124 ),
	.C(n38),
	.B(\u_datapath/n113 ),
	.A(n87));
   OAI21X1 \u_datapath/U149  (.Y(\u_datapath/n112 ),
	.C(n23),
	.B(\u_datapath/n125 ),
	.A(n110));
   OAI22X1 \u_datapath/U148  (.Y(\u_datapath/n224 ),
	.D(\u_datapath/n124 ),
	.C(n39),
	.B(\u_datapath/n112 ),
	.A(n88));
   OAI21X1 \u_datapath/U147  (.Y(\u_datapath/n121 ),
	.C(\u_datapath/n118 ),
	.B(\u_datapath/n123 ),
	.A(\u_datapath/n122 ));
   NAND2X1 \u_datapath/U146  (.Y(\u_datapath/n120 ),
	.B(rst_n),
	.A(\u_datapath/n121 ));
   OAI22X1 \u_datapath/U145  (.Y(\u_datapath/n223 ),
	.D(\u_datapath/n120 ),
	.C(n37),
	.B(\u_datapath/n114 ),
	.A(n82));
   OAI22X1 \u_datapath/U144  (.Y(\u_datapath/n222 ),
	.D(\u_datapath/n120 ),
	.C(n36),
	.B(\u_datapath/n116 ),
	.A(n85));
   OAI22X1 \u_datapath/U143  (.Y(\u_datapath/n221 ),
	.D(\u_datapath/n120 ),
	.C(n38),
	.B(\u_datapath/n113 ),
	.A(n83));
   OAI22X1 \u_datapath/U142  (.Y(\u_datapath/n220 ),
	.D(\u_datapath/n120 ),
	.C(n39),
	.B(\u_datapath/n112 ),
	.A(n84));
   XNOR2X1 \u_datapath/U141  (.Y(\u_datapath/n117 ),
	.B(\u_datapath/n119 ),
	.A(\u_datapath/n118 ));
   NAND2X1 \u_datapath/U140  (.Y(\u_datapath/n115 ),
	.B(rst_n),
	.A(\u_datapath/n117 ));
   OAI22X1 \u_datapath/U139  (.Y(\u_datapath/n219 ),
	.D(\u_datapath/n114 ),
	.C(n78),
	.B(\u_datapath/n115 ),
	.A(n37));
   OAI22X1 \u_datapath/U138  (.Y(\u_datapath/n218 ),
	.D(\u_datapath/n116 ),
	.C(n81),
	.B(\u_datapath/n115 ),
	.A(n36));
   OAI22X1 \u_datapath/U137  (.Y(\u_datapath/n217 ),
	.D(\u_datapath/n113 ),
	.C(n79),
	.B(\u_datapath/n115 ),
	.A(n38));
   OAI22X1 \u_datapath/U136  (.Y(\u_datapath/n216 ),
	.D(\u_datapath/n112 ),
	.C(n80),
	.B(\u_datapath/n115 ),
	.A(n39));
   OAI22X1 \u_datapath/U135  (.Y(\u_datapath/n215 ),
	.D(\u_datapath/n114 ),
	.C(n76),
	.B(n37),
	.A(\u_datapath/n111 ));
   OAI22X1 \u_datapath/U134  (.Y(\u_datapath/n214 ),
	.D(\u_datapath/n113 ),
	.C(n90),
	.B(n38),
	.A(\u_datapath/n111 ));
   OAI22X1 \u_datapath/U133  (.Y(\u_datapath/n213 ),
	.D(\u_datapath/n112 ),
	.C(n77),
	.B(n39),
	.A(\u_datapath/n111 ));
   NAND2X1 \u_datapath/U127  (.Y(\u_datapath/price_sel[1] ),
	.B(n111),
	.A(n110));
   AND2X2 \u_datapath/U48  (.Y(can10),
	.B(\u_datapath/n208 ),
	.A(\u_datapath/n207 ));
   AND2X2 \u_datapath/U47  (.Y(can25),
	.B(\u_datapath/N24 ),
	.A(\u_datapath/N25 ));
   AND2X2 \u_datapath/U46  (.Y(\u_datapath/coin_value [2]),
	.B(coin_type[1]),
	.A(n49));
   AND2X2 \u_datapath/U45  (.Y(\u_datapath/n122 ),
	.B(\u_datapath/n202 ),
	.A(\u_datapath/n201 ));
   AND2X2 \u_datapath/U44  (.Y(\u_datapath/n123 ),
	.B(\u_datapath/n200 ),
	.A(\u_datapath/n199 ));
   AND2X2 \u_datapath/U42  (.Y(\u_datapath/n131 ),
	.B(\u_datapath/n155 ),
	.A(do_load_rem_from_bal));
   AND2X2 \u_datapath/U41  (.Y(\u_datapath/n111 ),
	.B(n23),
	.A(\u_datapath/n126 ));
   DFFNEGX1 \u_datapath/inv_reg[0][3]  (.Q(\u_datapath/inv[0][3] ),
	.D(\u_datapath/n228 ),
	.CLK(n29));
   DFFNEGX1 \u_datapath/inv_reg[3][3]  (.Q(\u_datapath/inv[3][3] ),
	.D(\u_datapath/n215 ),
	.CLK(n28));
   DFFNEGX1 \u_datapath/inv_reg[2][3]  (.Q(\u_datapath/inv[2][3] ),
	.D(\u_datapath/n213 ),
	.CLK(n28));
   DFFNEGX1 \u_datapath/inv_reg[3][2]  (.Q(\u_datapath/inv[3][2] ),
	.D(\u_datapath/n219 ),
	.CLK(clkb));
   DFFNEGX1 \u_datapath/inv_reg[1][2]  (.Q(\u_datapath/inv[1][2] ),
	.D(\u_datapath/n217 ),
	.CLK(clkb));
   DFFNEGX1 \u_datapath/inv_reg[2][2]  (.Q(\u_datapath/inv[2][2] ),
	.D(\u_datapath/n216 ),
	.CLK(clkb));
   DFFNEGX1 \u_datapath/inv_reg[0][2]  (.Q(\u_datapath/inv[0][2] ),
	.D(\u_datapath/n218 ),
	.CLK(clkb));
   DFFNEGX1 \u_datapath/inv_reg[3][1]  (.Q(\u_datapath/inv[3][1] ),
	.D(\u_datapath/n223 ),
	.CLK(clkb));
   DFFNEGX1 \u_datapath/inv_reg[1][1]  (.Q(\u_datapath/inv[1][1] ),
	.D(\u_datapath/n221 ),
	.CLK(clkb));
   DFFNEGX1 \u_datapath/inv_reg[2][1]  (.Q(\u_datapath/inv[2][1] ),
	.D(\u_datapath/n220 ),
	.CLK(clkb));
   DFFNEGX1 \u_datapath/inv_reg[0][1]  (.Q(\u_datapath/inv[0][1] ),
	.D(\u_datapath/n222 ),
	.CLK(n29));
   DFFNEGX1 \u_datapath/inv_reg[3][0]  (.Q(\u_datapath/inv[3][0] ),
	.D(\u_datapath/n227 ),
	.CLK(n29));
   DFFNEGX1 \u_datapath/inv_reg[1][0]  (.Q(\u_datapath/inv[1][0] ),
	.D(\u_datapath/n225 ),
	.CLK(n29));
   DFFNEGX1 \u_datapath/inv_reg[2][0]  (.Q(\u_datapath/inv[2][0] ),
	.D(\u_datapath/n224 ),
	.CLK(n29));
   DFFNEGX1 \u_datapath/inv_reg[0][0]  (.Q(\u_datapath/inv[0][0] ),
	.D(\u_datapath/n226 ),
	.CLK(n29));
   DFFNEGX1 \u_datapath/inv_reg[1][3]  (.Q(\u_datapath/inv[1][3] ),
	.D(\u_datapath/n214 ),
	.CLK(n29));
   DFFNEGX1 \u_datapath/change_rem_reg[2]  (.Q(\u_datapath/change_rem_out[2] ),
	.D(\u_datapath/n232 ),
	.CLK(n29));
   DFFNEGX1 \u_datapath/change_rem_reg[1]  (.Q(\u_datapath/change_rem_out[1] ),
	.D(\u_datapath/n233 ),
	.CLK(n29));
   DFFNEGX1 \u_datapath/change_rem_reg[0]  (.Q(\u_datapath/N86 ),
	.D(\u_datapath/n234 ),
	.CLK(n29));
   DFFNEGX1 \u_datapath/change_rem_reg[3]  (.Q(\u_datapath/change_rem_out[3] ),
	.D(\u_datapath/n231 ),
	.CLK(n29));
   DFFNEGX1 \u_datapath/change_rem_reg[4]  (.Q(\u_datapath/change_rem_out[4] ),
	.D(\u_datapath/n230 ),
	.CLK(n29));
   DFFNEGX1 \u_datapath/change_rem_reg[5]  (.Q(\u_datapath/change_rem_out[5] ),
	.D(\u_datapath/n229 ),
	.CLK(n29));
   DFFNEGX1 \u_datapath/sel_reg_reg[0]  (.Q(sel_reg_out[0]),
	.D(\u_datapath/n235 ),
	.CLK(n29));
   DFFNEGX1 \u_datapath/sel_reg_reg[1]  (.Q(sel_reg_out[1]),
	.D(\u_datapath/n236 ),
	.CLK(n28));
   DFFNEGX1 \u_datapath/balance_reg[5]  (.Q(\u_datapath/balance_out[5] ),
	.D(\u_datapath/n237 ),
	.CLK(n28));
   DFFNEGX1 \u_datapath/balance_reg[4]  (.Q(\u_datapath/balance_out[4] ),
	.D(\u_datapath/n238 ),
	.CLK(n28));
   DFFNEGX1 \u_datapath/balance_reg[3]  (.Q(\u_datapath/balance_out[3] ),
	.D(\u_datapath/n239 ),
	.CLK(n28));
   DFFNEGX1 \u_datapath/balance_reg[2]  (.Q(\u_datapath/balance_out[2] ),
	.D(\u_datapath/n240 ),
	.CLK(n28));
   DFFNEGX1 \u_datapath/balance_reg[1]  (.Q(\u_datapath/balance_out[1] ),
	.D(\u_datapath/n241 ),
	.CLK(n28));
   DFFNEGX1 \u_datapath/balance_reg[0]  (.Q(\u_datapath/N50 ),
	.D(\u_datapath/n242 ),
	.CLK(n28));
   DFFNEGX1 \u_datapath/change_bank_reg[3]  (.Q(\u_datapath/change_bank [3]),
	.D(\u_datapath/n245 ),
	.CLK(n28));
   DFFNEGX1 \u_datapath/change_bank_reg[2]  (.Q(\u_datapath/change_bank [2]),
	.D(\u_datapath/n246 ),
	.CLK(n28));
   DFFNEGX1 \u_datapath/change_bank_reg[1]  (.Q(\u_datapath/change_bank [1]),
	.D(\u_datapath/n247 ),
	.CLK(n28));
   DFFNEGX1 \u_datapath/change_bank_reg[4]  (.Q(\u_datapath/change_bank [4]),
	.D(\u_datapath/n244 ),
	.CLK(n28));
   DFFNEGX1 \u_datapath/change_bank_reg[5]  (.Q(\u_datapath/change_bank [5]),
	.D(\u_datapath/n243 ),
	.CLK(n28));
   DFFNEGX1 \u_datapath/change_bank_reg[0]  (.Q(\u_datapath/N92 ),
	.D(\u_datapath/n248 ),
	.CLK(n28));
   FAX1 \u_datapath/add_94/U1_1  (.YS(\u_datapath/N31 ),
	.YC(\u_datapath/add_94/carry [2]),
	.C(n9),
	.B(\u_datapath/coin_value [1]),
	.A(\u_datapath/balance_out[1] ));
   FAX1 \u_datapath/add_94/U1_2  (.YS(\u_datapath/N32 ),
	.YC(\u_datapath/add_94/carry [3]),
	.C(\u_datapath/add_94/carry [2]),
	.B(\u_datapath/coin_value [2]),
	.A(\u_datapath/balance_out[2] ));
   FAX1 \u_datapath/sub_103/U2_2  (.YS(\u_datapath/N52 ),
	.YC(\u_datapath/sub_103/carry [3]),
	.C(\u_datapath/sub_103/carry [2]),
	.B(n2),
	.A(\u_datapath/balance_out[2] ));
   FAX1 \u_datapath/sub_103/U2_3  (.YS(\u_datapath/N53 ),
	.YC(\u_datapath/sub_103/carry [4]),
	.C(\u_datapath/sub_103/carry [3]),
	.B(n5),
	.A(\u_datapath/balance_out[3] ));
   AND2X2 U1 (.Y(n1),
	.B(n57),
	.A(chg_denom[0]));
   AND2X2 U2 (.Y(n2),
	.B(n111),
	.A(n106));
   OR2X2 U3 (.Y(n3),
	.B(chg_denom[1]),
	.A(chg_denom[0]));
   AND2X2 U4 (.Y(n4),
	.B(n23),
	.A(\u_datapath/n195 ));
   AND2X2 U5 (.Y(n5),
	.B(n107),
	.A(\u_datapath/n103 ));
   AND2X2 U6 (.Y(n6),
	.B(\u_datapath/change_rem_out[2] ),
	.A(\u_datapath/sub_111/carry[2] ));
   AND2X2 U7 (.Y(n7),
	.B(\u_datapath/balance_out[3] ),
	.A(\u_datapath/add_94/carry [3]));
   AND2X2 U8 (.Y(n8),
	.B(\u_datapath/change_bank [2]),
	.A(\u_datapath/sub_112/carry[2] ));
   AND2X2 U9 (.Y(n9),
	.B(\u_datapath/N50 ),
	.A(n49));
   AND2X2 U10 (.Y(n10),
	.B(\u_datapath/balance_out[4] ),
	.A(n7));
   XOR2X1 U11 (.Y(n11),
	.B(\u_datapath/change_rem_out[4] ),
	.A(\u_datapath/sub_111/carry[4] ));
   XOR2X1 U12 (.Y(n12),
	.B(\u_datapath/change_rem_out[1] ),
	.A(\u_datapath/N86 ));
   XNOR2X1 U13 (.Y(n13),
	.B(\u_datapath/change_rem_out[2] ),
	.A(\u_datapath/sub_111/carry[2] ));
   XOR2X1 U14 (.Y(n14),
	.B(\u_datapath/change_rem_out[3] ),
	.A(n6));
   XOR2X1 U15 (.Y(n15),
	.B(\u_datapath/change_bank [4]),
	.A(\u_datapath/sub_112/carry[4] ));
   XOR2X1 U16 (.Y(n16),
	.B(\u_datapath/sub_111/carry[5] ),
	.A(\u_datapath/change_rem_out[5] ));
   XOR2X1 U17 (.Y(n17),
	.B(\u_datapath/sub_112/carry[5] ),
	.A(\u_datapath/change_bank [5]));
   XNOR2X1 U18 (.Y(n18),
	.B(\u_datapath/change_bank [2]),
	.A(\u_datapath/sub_112/carry[2] ));
   INVX2 U19 (.Y(n23),
	.A(n24));
   BUFX2 U20 (.Y(n25),
	.A(n27));
   BUFX2 U21 (.Y(n24),
	.A(n27));
   BUFX2 U22 (.Y(n26),
	.A(n27));
   INVX2 U23 (.Y(n54),
	.A(\u_datapath/n185 ));
   INVX2 U24 (.Y(n28),
	.A(n30));
   INVX2 U25 (.Y(n29),
	.A(n30));
   INVX2 U26 (.Y(n27),
	.A(rst_n));
   INVX2 U27 (.Y(n30),
	.A(clkb));
   INVX2 U28 (.Y(n22),
	.A(n3));
   INVX2 U29 (.Y(n19),
	.A(\u_datapath/change_bank [4]));
   INVX2 U30 (.Y(n20),
	.A(\u_datapath/change_bank [2]));
   INVX2 U31 (.Y(n21),
	.A(n4));
   OR2X1 U32 (.Y(\u_datapath/sub_103/carry [5]),
	.B(\u_datapath/sub_103/carry [4]),
	.A(\u_datapath/balance_out[4] ));
   XNOR2X1 U33 (.Y(\u_datapath/N54 ),
	.B(\u_datapath/balance_out[4] ),
	.A(\u_datapath/sub_103/carry [4]));
   XNOR2X1 U34 (.Y(\u_datapath/N55 ),
	.B(\u_datapath/sub_103/carry [5]),
	.A(\u_datapath/balance_out[5] ));
   OR2X1 U35 (.Y(\u_datapath/sub_103/carry [2]),
	.B(n109),
	.A(\u_datapath/balance_out[1] ));
   XNOR2X1 U36 (.Y(\u_datapath/N51 ),
	.B(\u_datapath/balance_out[1] ),
	.A(n109));
   OR2X1 U37 (.Y(\u_datapath/sub_111/carry[2] ),
	.B(\u_datapath/N86 ),
	.A(\u_datapath/change_rem_out[1] ));
   OR2X1 U38 (.Y(\u_datapath/sub_111/carry[4] ),
	.B(n6),
	.A(\u_datapath/change_rem_out[3] ));
   OR2X1 U39 (.Y(\u_datapath/sub_111/carry[5] ),
	.B(\u_datapath/sub_111/carry[4] ),
	.A(\u_datapath/change_rem_out[4] ));
   OR2X1 U40 (.Y(\u_datapath/sub_112/carry[2] ),
	.B(\u_datapath/N92 ),
	.A(\u_datapath/change_bank [1]));
   XNOR2X1 U41 (.Y(\u_datapath/N81 ),
	.B(\u_datapath/change_bank [1]),
	.A(\u_datapath/N92 ));
   OR2X1 U42 (.Y(\u_datapath/sub_112/carry[4] ),
	.B(n8),
	.A(\u_datapath/change_bank [3]));
   XNOR2X1 U43 (.Y(\u_datapath/N83 ),
	.B(\u_datapath/change_bank [3]),
	.A(n8));
   OR2X1 U44 (.Y(\u_datapath/sub_112/carry[5] ),
	.B(\u_datapath/sub_112/carry[4] ),
	.A(\u_datapath/change_bank [4]));
   OR2X1 U45 (.Y(\u_datapath/sub_115/carry [3]),
	.B(\u_datapath/change_rem_out[1] ),
	.A(\u_datapath/change_rem_out[2] ));
   XNOR2X1 U46 (.Y(\u_datapath/N88 ),
	.B(\u_datapath/change_rem_out[2] ),
	.A(\u_datapath/change_rem_out[1] ));
   OR2X1 U47 (.Y(\u_datapath/sub_115/carry [4]),
	.B(\u_datapath/sub_115/carry [3]),
	.A(\u_datapath/change_rem_out[3] ));
   XNOR2X1 U48 (.Y(\u_datapath/N89 ),
	.B(\u_datapath/change_rem_out[3] ),
	.A(\u_datapath/sub_115/carry [3]));
   OR2X1 U49 (.Y(\u_datapath/sub_115/carry [5]),
	.B(\u_datapath/sub_115/carry [4]),
	.A(\u_datapath/change_rem_out[4] ));
   XNOR2X1 U50 (.Y(\u_datapath/N90 ),
	.B(\u_datapath/change_rem_out[4] ),
	.A(\u_datapath/sub_115/carry [4]));
   XNOR2X1 U51 (.Y(\u_datapath/N91 ),
	.B(\u_datapath/sub_115/carry [5]),
	.A(\u_datapath/change_rem_out[5] ));
   OR2X1 U52 (.Y(\u_datapath/sub_116/carry [3]),
	.B(\u_datapath/change_bank [1]),
	.A(\u_datapath/change_bank [2]));
   XNOR2X1 U53 (.Y(\u_datapath/N94 ),
	.B(\u_datapath/change_bank [2]),
	.A(\u_datapath/change_bank [1]));
   OR2X1 U54 (.Y(\u_datapath/sub_116/carry [4]),
	.B(\u_datapath/sub_116/carry [3]),
	.A(\u_datapath/change_bank [3]));
   XNOR2X1 U55 (.Y(\u_datapath/N95 ),
	.B(\u_datapath/change_bank [3]),
	.A(\u_datapath/sub_116/carry [3]));
   OR2X1 U56 (.Y(\u_datapath/sub_116/carry [5]),
	.B(\u_datapath/sub_116/carry [4]),
	.A(\u_datapath/change_bank [4]));
   XNOR2X1 U57 (.Y(\u_datapath/N96 ),
	.B(\u_datapath/change_bank [4]),
	.A(\u_datapath/sub_116/carry [4]));
   XNOR2X1 U58 (.Y(\u_datapath/N97 ),
	.B(\u_datapath/sub_116/carry [5]),
	.A(\u_datapath/change_bank [5]));
   XOR2X1 U59 (.Y(\u_datapath/N30 ),
	.B(\u_datapath/N50 ),
	.A(n49));
   XOR2X1 U60 (.Y(\u_datapath/N33 ),
	.B(\u_datapath/balance_out[3] ),
	.A(\u_datapath/add_94/carry [3]));
   XOR2X1 U61 (.Y(\u_datapath/N34 ),
	.B(\u_datapath/balance_out[4] ),
	.A(n7));
   XOR2X1 U62 (.Y(\u_datapath/N35 ),
	.B(n10),
	.A(\u_datapath/balance_out[5] ));
   INVX2 U63 (.Y(n31),
	.A(\u_fsm/N200 ));
   INVX2 U64 (.Y(n32),
	.A(\u_fsm/N203 ));
   INVX2 U65 (.Y(n33),
	.A(\u_datapath/n159 ));
   INVX2 U66 (.Y(n34),
	.A(\u_datapath/n155 ));
   INVX2 U67 (.Y(n35),
	.A(\u_datapath/n172 ));
   INVX2 U68 (.Y(n36),
	.A(\u_datapath/n116 ));
   INVX2 U69 (.Y(n37),
	.A(\u_datapath/n114 ));
   INVX2 U70 (.Y(n38),
	.A(\u_datapath/n113 ));
   INVX2 U71 (.Y(n39),
	.A(\u_datapath/n112 ));
   INVX2 U72 (.Y(n40),
	.A(\u_fsm/n92 ));
   INVX2 U73 (.Y(n41),
	.A(\u_fsm/n91 ));
   INVX2 U74 (.Y(n42),
	.A(\u_fsm/n84 ));
   INVX2 U75 (.Y(n43),
	.A(\u_fsm/n52 ));
   INVX2 U76 (.Y(n44),
	.A(\u_fsm/n43 ));
   INVX2 U77 (.Y(n45),
	.A(\u_fsm/n34 ));
   INVX2 U78 (.Y(n46),
	.A(\u_fsm/n55 ));
   INVX2 U79 (.Y(n47),
	.A(coin_valid));
   INVX2 U80 (.Y(n48),
	.A(\u_fsm/n37 ));
   INVX2 U81 (.Y(n49),
	.A(coin_type[0]));
   INVX2 U82 (.Y(n50),
	.A(sel_valid));
   INVX2 U83 (.Y(n51),
	.A(\u_fsm/n42 ));
   INVX2 U84 (.Y(n52),
	.A(cancel));
   INVX2 U85 (.Y(n53),
	.A(chg_sub_pulse));
   INVX2 U86 (.Y(n55),
	.A(\u_datapath/n191 ));
   INVX2 U87 (.Y(n56),
	.A(\u_datapath/n184 ));
   INVX2 U88 (.Y(n57),
	.A(chg_denom[1]));
   INVX2 U89 (.Y(n58),
	.A(do_clear_balance));
   INVX2 U90 (.Y(n59),
	.A(\u_fsm/n58 ));
   INVX2 U91 (.Y(n60),
	.A(\u_fsm/n85 ));
   INVX2 U92 (.Y(n61),
	.A(\u_fsm/n50 ));
   INVX2 U93 (.Y(n62),
	.A(\u_fsm/n89 ));
   INVX2 U94 (.Y(n63),
	.A(\u_fsm/state [1]));
   INVX2 U95 (.Y(n64),
	.A(\u_fsm/n51 ));
   INVX2 U96 (.Y(n65),
	.A(\u_fsm/state [0]));
   INVX2 U97 (.Y(n66),
	.A(\u_fsm/n67 ));
   INVX2 U98 (.Y(n67),
	.A(\u_fsm/n66 ));
   INVX2 U99 (.Y(n68),
	.A(\u_fsm/cstate [2]));
   INVX2 U100 (.Y(n69),
	.A(\u_fsm/n72 ));
   INVX2 U101 (.Y(n70),
	.A(\u_fsm/n80 ));
   INVX2 U102 (.Y(n71),
	.A(\u_fsm/n83 ));
   INVX2 U103 (.Y(n72),
	.A(\u_fsm/cstate [1]));
   INVX2 U104 (.Y(n73),
	.A(\u_fsm/cstate [0]));
   INVX2 U105 (.Y(n74),
	.A(\u_datapath/inv[0][3] ));
   INVX2 U106 (.Y(n75),
	.A(soldout));
   INVX2 U107 (.Y(n76),
	.A(\u_datapath/inv[3][3] ));
   INVX2 U108 (.Y(n77),
	.A(\u_datapath/inv[2][3] ));
   INVX2 U109 (.Y(n78),
	.A(\u_datapath/inv[3][2] ));
   INVX2 U110 (.Y(n79),
	.A(\u_datapath/inv[1][2] ));
   INVX2 U111 (.Y(n80),
	.A(\u_datapath/inv[2][2] ));
   INVX2 U112 (.Y(n81),
	.A(\u_datapath/inv[0][2] ));
   INVX2 U113 (.Y(n82),
	.A(\u_datapath/inv[3][1] ));
   INVX2 U114 (.Y(n83),
	.A(\u_datapath/inv[1][1] ));
   INVX2 U115 (.Y(n84),
	.A(\u_datapath/inv[2][1] ));
   INVX2 U116 (.Y(n85),
	.A(\u_datapath/inv[0][1] ));
   INVX2 U117 (.Y(n86),
	.A(\u_datapath/inv[3][0] ));
   INVX2 U118 (.Y(n87),
	.A(\u_datapath/inv[1][0] ));
   INVX2 U119 (.Y(n88),
	.A(\u_datapath/inv[2][0] ));
   INVX2 U120 (.Y(n89),
	.A(\u_datapath/inv[0][0] ));
   INVX2 U121 (.Y(n90),
	.A(\u_datapath/inv[1][3] ));
   INVX2 U122 (.Y(n91),
	.A(n133));
   INVX2 U123 (.Y(n92),
	.A(bank_enough));
   INVX2 U124 (.Y(n93),
	.A(n147));
   INVX2 U125 (.Y(n94),
	.A(\u_datapath/change_rem_out[2] ));
   INVX2 U126 (.Y(n95),
	.A(rem_zero));
   INVX2 U127 (.Y(n96),
	.A(can5));
   INVX2 U128 (.Y(n97),
	.A(\u_datapath/change_rem_out[1] ));
   INVX2 U129 (.Y(n98),
	.A(n142));
   INVX2 U130 (.Y(n99),
	.A(\u_datapath/N86 ));
   INVX2 U131 (.Y(n100),
	.A(n143));
   INVX2 U132 (.Y(n101),
	.A(\u_datapath/change_rem_out[3] ));
   INVX2 U133 (.Y(n102),
	.A(\u_datapath/change_rem_out[4] ));
   INVX2 U134 (.Y(n103),
	.A(n151));
   INVX2 U135 (.Y(n104),
	.A(\u_datapath/change_rem_out[5] ));
   INVX2 U136 (.Y(n105),
	.A(n152));
   INVX2 U137 (.Y(n106),
	.A(\u_datapath/n100 ));
   INVX2 U138 (.Y(n107),
	.A(\u_datapath/n98 ));
   INVX2 U139 (.Y(n108),
	.A(sel_reg_out[0]));
   INVX2 U140 (.Y(n109),
	.A(\u_datapath/price_sel[1] ));
   INVX2 U141 (.Y(n110),
	.A(\u_datapath/n99 ));
   INVX2 U142 (.Y(n111),
	.A(\u_datapath/n97 ));
   INVX2 U143 (.Y(n112),
	.A(sel_reg_out[1]));
   INVX2 U144 (.Y(n113),
	.A(\u_datapath/balance_out[5] ));
   INVX2 U145 (.Y(n114),
	.A(\u_datapath/balance_out[4] ));
   INVX2 U146 (.Y(n115),
	.A(\u_datapath/balance_out[3] ));
   INVX2 U147 (.Y(n116),
	.A(\u_datapath/balance_out[2] ));
   INVX2 U148 (.Y(n117),
	.A(\u_datapath/balance_out[1] ));
   INVX2 U149 (.Y(n118),
	.A(\u_datapath/N50 ));
   INVX2 U150 (.Y(n119),
	.A(\u_datapath/N107 ));
   INVX2 U151 (.Y(n120),
	.A(\u_datapath/n208 ));
   INVX2 U152 (.Y(n121),
	.A(\u_datapath/change_bank [3]));
   INVX2 U153 (.Y(n122),
	.A(n128));
   INVX2 U154 (.Y(n123),
	.A(\u_datapath/N105 ));
   INVX2 U155 (.Y(n124),
	.A(\u_datapath/change_bank [1]));
   INVX2 U156 (.Y(n125),
	.A(\u_datapath/change_bank [5]));
   INVX2 U157 (.Y(n126),
	.A(\u_datapath/N92 ));
   NAND2X1 U158 (.Y(n127),
	.B(n126),
	.A(n124));
   OAI21X1 U159 (.Y(\u_datapath/N105 ),
	.C(n127),
	.B(n124),
	.A(n126));
   NOR2X1 U160 (.Y(n129),
	.B(\u_datapath/change_bank [2]),
	.A(n127));
   AOI21X1 U161 (.Y(n128),
	.C(n129),
	.B(\u_datapath/change_bank [2]),
	.A(n127));
   NAND2X1 U162 (.Y(n130),
	.B(n121),
	.A(n129));
   OAI21X1 U163 (.Y(\u_datapath/N107 ),
	.C(n130),
	.B(n121),
	.A(n129));
   XNOR2X1 U164 (.Y(\u_datapath/N108 ),
	.B(n130),
	.A(\u_datapath/change_bank [4]));
   NOR2X1 U165 (.Y(n131),
	.B(n130),
	.A(\u_datapath/change_bank [4]));
   XOR2X1 U166 (.Y(\u_datapath/N109 ),
	.B(n131),
	.A(\u_datapath/change_bank [5]));
   NAND2X1 U167 (.Y(n132),
	.B(n99),
	.A(n97));
   OAI21X1 U168 (.Y(\u_datapath/N99 ),
	.C(n132),
	.B(n97),
	.A(n99));
   NOR2X1 U169 (.Y(n134),
	.B(\u_datapath/change_rem_out[2] ),
	.A(n132));
   AOI21X1 U170 (.Y(n133),
	.C(n134),
	.B(\u_datapath/change_rem_out[2] ),
	.A(n132));
   NAND2X1 U171 (.Y(n135),
	.B(n101),
	.A(n134));
   OAI21X1 U172 (.Y(\u_datapath/N101 ),
	.C(n135),
	.B(n101),
	.A(n134));
   XNOR2X1 U173 (.Y(\u_datapath/N102 ),
	.B(n135),
	.A(\u_datapath/change_rem_out[4] ));
   NOR2X1 U174 (.Y(n136),
	.B(n135),
	.A(\u_datapath/change_rem_out[4] ));
   XOR2X1 U175 (.Y(\u_datapath/N103 ),
	.B(n136),
	.A(\u_datapath/change_rem_out[5] ));
   OAI21X1 U176 (.Y(n138),
	.C(\u_datapath/change_bank [2]),
	.B(\u_datapath/change_bank [1]),
	.A(\u_datapath/N92 ));
   NOR2X1 U177 (.Y(n137),
	.B(\u_datapath/change_bank [4]),
	.A(\u_datapath/change_bank [5]));
   NAND3X1 U178 (.Y(\u_datapath/N25 ),
	.C(n137),
	.B(n121),
	.A(n138));
   OAI21X1 U179 (.Y(n140),
	.C(\u_datapath/change_rem_out[2] ),
	.B(\u_datapath/change_rem_out[1] ),
	.A(\u_datapath/N86 ));
   NOR2X1 U180 (.Y(n139),
	.B(\u_datapath/change_rem_out[4] ),
	.A(\u_datapath/change_rem_out[5] ));
   NAND3X1 U181 (.Y(\u_datapath/N24 ),
	.C(n139),
	.B(n101),
	.A(n140));
   NOR2X1 U182 (.Y(n151),
	.B(\u_datapath/change_bank [5]),
	.A(n104));
   AOI22X1 U183 (.Y(n150),
	.D(n104),
	.C(\u_datapath/change_bank [5]),
	.B(n102),
	.A(\u_datapath/change_bank [4]));
   OAI21X1 U184 (.Y(n149),
	.C(n103),
	.B(n102),
	.A(\u_datapath/change_bank [4]));
   NAND2X1 U185 (.Y(n143),
	.B(n121),
	.A(\u_datapath/change_rem_out[3] ));
   NAND3X1 U186 (.Y(n141),
	.C(\u_datapath/change_bank [2]),
	.B(n94),
	.A(n143));
   OAI21X1 U187 (.Y(n147),
	.C(n141),
	.B(n121),
	.A(\u_datapath/change_rem_out[3] ));
   AOI22X1 U188 (.Y(n142),
	.D(\u_datapath/N86 ),
	.C(n126),
	.B(\u_datapath/change_rem_out[1] ),
	.A(n124));
   OAI21X1 U189 (.Y(n146),
	.C(n98),
	.B(n124),
	.A(\u_datapath/change_rem_out[1] ));
   NOR2X1 U190 (.Y(n144),
	.B(n94),
	.A(\u_datapath/change_bank [2]));
   OAI21X1 U191 (.Y(n145),
	.C(n93),
	.B(n144),
	.A(n100));
   OAI21X1 U192 (.Y(n148),
	.C(n145),
	.B(n146),
	.A(n147));
   OAI22X1 U193 (.Y(bank_enough),
	.D(n148),
	.C(n149),
	.B(n150),
	.A(n151));
   OAI22X1 U194 (.Y(n152),
	.D(\u_datapath/balance_out[2] ),
	.C(n2),
	.B(\u_datapath/balance_out[3] ),
	.A(n5));
   AOI21X1 U195 (.Y(n153),
	.C(\u_datapath/balance_out[1] ),
	.B(n2),
	.A(\u_datapath/balance_out[2] ));
   NAND2X1 U196 (.Y(n154),
	.B(\u_datapath/price_sel[1] ),
	.A(n153));
   AOI22X1 U197 (.Y(n156),
	.D(n154),
	.C(n105),
	.B(n5),
	.A(\u_datapath/balance_out[3] ));
   NOR2X1 U198 (.Y(n155),
	.B(\u_datapath/balance_out[4] ),
	.A(\u_datapath/balance_out[5] ));
   NAND2X1 U199 (.Y(enough),
	.B(n155),
	.A(n156));
   NOR2X1 U200 (.Y(\u_datapath/n103 ),
	.B(\u_datapath/n100 ),
	.A(\u_datapath/n99 ));
endmodule

